
[homes]
   comment = Home Directory
   browseable = yes
   read only = no
   create mask = 0700
   directory mask = 0700
   valid users = %S

[public]
   comment = Public Share
   path = /srv/samba/public
   browseable = yes
   guest ok = yes
   read only = no
   writable = yes
   create mask = 0777
   directory mask = 0777
   force user = nobody
   force group = users
