[global]
   workgroup = WORKGROUP
   server string = Samba Server
   server role = standalone server
   security = user
   map to guest = Bad User
   log file = /var/log/samba/%m.log
   max log size = 50
   client min protocol = SMB2
   server min protocol = SMB2
